version: '2'

services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: ${APP_ENV}
      XDEBUG_HOST: ${XDEBUG_HOST}

  composer:
    command: ['composer', 'install', '--no-interaction']
    working_dir: /var/www/html
    extends:
      file: docker-compose.base.yml
      service: app
    volumes:
      - ./:/var/www/html

  yarn:
    command: ['yarn', 'install']
    extends:
      file: docker-compose.base.yml
      service: node
    volumes:
      - ./:/var/www/html

  gulp:
    command: ["node_modules/.bin/gulp", 'watch']
    working_dir: /var/www/html
    extends:
      file: docker-compose.base.yml
      service: node
    depends_on:
      - yarn
    volumes:
      - ./:/var/www/html

  elasticsearch:
    extends:
      file: docker-compose.base.yml
      service: elasticsearch

  mailhog:
    build:
      context: ./docker/mailhog
      dockerfile: Dockerfile
    image: wearejust/mailhog
    ports:
        - "8025:8025"
    networks:
    - sdnet
    
  mysql:
    extends:
        file: docker-compose.base.yml
        service: mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"

  node:
    extends:
      file: docker-compose.base.yml
      service: node
      
networks:
  sdnet:
    driver: "bridge"

volumes:
  mysql_data:
    driver: "local"
  elasticsearch_data:
    driver: "local"
