version: '2.1'

services:

  app:
    image: wearejust/nginx:1.0
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on: 
      - php
    networks:
      - sdnet

  php:
    extends:
      file: docker-compose.base.yml
      service: php

  composer:
    extends:
      file: docker-compose.base.yml
      service: php
    command: ['composer', 'install']      

  gulp:
    command: bash -c "yarn install && node_modules/.bin/gulp watch"
    extends:
      file: docker-compose.base.yml
      service: node

  mailhog:
    image: mailhog/mailhog:latest
    ports:
        - "8025:8025"
    networks:
    - sdnet

  browsersync:
    image: ustwo/browser-sync:latest
    command: start --proxy "app.${DOMAIN}" --files "public/css/*.css"
    volumes:
      - ./:/source
    ports:
      - "3000:3000"
      - "3001:3001"
      
  mysql:
    extends:
        file: docker-compose.base.yml
        service: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"

networks:
  sdnet:
    driver: "bridge"

volumes:
  mysql_data:
    driver: "local"
